### ISSUE TITLE
💡 -d 안티 디버거 옵션 구현 - 로직1(훈영)

### ISSUE THREAD

**Issue by ysbeam** [UDTKDT/Anti_Virus#30]

**Comment by hunyoungcha** [comment]
[동작 방식]

    1. ./UdkdAgent -d proc
    2. /proc 경로에서 현재 동작중인 프로세스의 pid를 모두 확인
    3. 각 pid 디렉터리의 comm 파일을 확인하여 프로세스가 실행할 때의 이름을 확인
    4. 확인 된 이름이 디버거로 지정되어 있는 이름과 동일할 경우 해당 프로세스를 kill하여 디버거를 종료 시킴



[UdkdAgent를 대상으로 gdb 실행]
![Image](https://github.com/UDTKDT/Anti_Virus/assets/63577348/1dd0b8f3-386e-4c84-b20a-0a24c2da8798)


[-d 옵션 실행 시]

![Image](https://github.com/UDTKDT/Anti_Virus/assets/63577348/506dcdcb-98d2-4e4c-b69f-e5bbb85c1255)



![Image](https://github.com/UDTKDT/Anti_Virus/assets/63577348/eb285834-703c-449d-85db-8f81a9b1a99c)
